"""Braille edition pages as one PDF plus a .tex that includes them (paper appendix).

Each TikZ page of render_braille_tikz.py is compiled on its own, because a full page exceeds XeTeX's main memory when
compiled inside the paper.

  python scripts/braille_edition/braille_edition_pages.py --tikz <paper>/figures/braille_edition_all.tex \
      --out <paper>/figures/braille_edition      # -> pages.pdf, pages.tex
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import tempfile
import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "src"))
from ubt.paths import WORK  # noqa: E402

TECTONIC = f"{WORK}/tools/tectonic"
PREAMBLE = r"""\documentclass[border=0pt]{standalone}
\usepackage{tikz}
\usepackage{xcolor}
\definecolor{dotink}{RGB}{20,20,20}
\definecolor{dotpale}{RGB}{205,205,205}
\definecolor{hlerr}{RGB}{244,124,124}
\definecolor{hlunc}{RGB}{250,221,128}
\definecolor{inkink}{RGB}{60,60,60}
\definecolor{inkerr}{RGB}{170,25,25}
\tikzset{doton/.style={dotink},dotoff/.style={dotpale},cellerr/.style={hlerr,opacity=0.85},cellunc/.style={hlunc,opacity=0.75}}
\begin{document}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tikz", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--tectonic", default=os.environ.get("TECTONIC", TECTONIC))
    a = ap.parse_args()
    import pymupdf  # noqa: PLC0415
    src = open(a.tikz, encoding="utf-8").read()
    pics = re.findall(r"\\begin\{tikzpicture\}.*?\\end\{tikzpicture\}", src, flags=re.S)
    caps = re.findall(r"\{\\footnotesize (Braille edition, page \d+ of \d+)\}", src)
    heights = re.findall(r"\\resizebox\{!\}\{([0-9.]+)\\textheight\}", src)   # the renderer's per-page scale
    assert pics and len(pics) == len(caps) == len(heights), (len(pics), len(caps), len(heights))
    os.makedirs(a.out, exist_ok=True)
    merged = pymupdf.open()
    with tempfile.TemporaryDirectory() as tmp:
        for i, pic in enumerate(pics, 1):
            tex = os.path.join(tmp, f"p{i}.tex")
            open(tex, "w", encoding="utf-8").write(PREAMBLE + pic + "\n\\end{document}\n")
            r = subprocess.run([a.tectonic, "-X", "compile", tex, "--outdir", tmp], capture_output=True, text=True)
            if r.returncode != 0:
                raise SystemExit(f"page {i} failed:\n{r.stderr[-2000:]}")
            merged.insert_pdf(pymupdf.open(os.path.join(tmp, f"p{i}.pdf")))
            print(f"page {i}/{len(pics)}", flush=True)
        merged.save(os.path.join(a.out, "pages.pdf"), garbage=4, deflate=True)
    with open(os.path.join(a.out, "pages.tex"), "w", encoding="utf-8") as fh:
        fh.write("% generated by scripts/braille_edition/braille_edition_pages.py (code repo) from figures/braille_edition_all.tex\n"
                 "% each page centred vertically with \\vspace*{\\fill} above and below\n")
        # one scale for all pages, the widest spanning the text width (the renderer's own scale overflows it)
        d = pymupdf.open(os.path.join(a.out, "pages.pdf"))
        wmax = max(pg.rect.width for pg in d)
        for i, (cap, pg) in enumerate(zip(caps, d), 1):
            fh.write("\\vspace*{\\fill}\n\\begin{center}\n\\includegraphics[page=" + str(i) + f",width={pg.rect.width / wmax:.4f}\\linewidth]"
                     "{figures/braille_edition/pages.pdf}\\\\[4pt]{\\footnotesize " + cap + "}\n\\end{center}\n\\vspace*{\\fill}\n\\clearpage\n")
    print("->", os.path.join(a.out, "pages.pdf"), shutil.os.path.getsize(os.path.join(a.out, "pages.pdf")) // 1024, "KB")


if __name__ == "__main__":
    main()
