"""Judge-score distribution for the appendix figure: share of documents at each judge score for four Table 1 systems.

Systems: GPT-5.5 few-shot, LibLouis backward, and UBT best-of-20 with the code inferred and with the oracle code, read
from the same per-document judge rows as Table 1 (an output with no text scores 1). A document's score is the expected
digit under the judge's probabilities over 1-5, binned by rounding (x.5 up). "empty" is the share of empty outputs.

  python scripts/paper/judge_dist_data.py [--paper <paper repo>]
      -> <paper>/figures/judge/judge_dist.dat, work/paper/judge_dist.json
"""
from __future__ import annotations

import argparse
import collections
import glob
import json
import math
import os
import sys

sys.path[:0] = sorted(glob.glob(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "*", "")))
from table1_ci import R, extra  # noqa: E402
from ubt.paths import PAPER  # noqa: E402
SYSTEMS = [   # key, Table 1 row, (model, rows name) as in table1_ci.py
    ("gpt55", "gpt55_fewshot", ("rlvr", "gpt55")),
    ("liblouis", "liblouis_given", ("rlvr", "liblouis")),
    ("ubt", "ours_bon", ("rlvr", "rlvr_V_agn")),
    ("ubt_oracle", "ours_bon_oracle_code", ("rlvr", "rlvr_V_given")),
]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--paper", default=PAPER)
    ap.add_argument("--json", default=f"{R}/paper/judge_dist.json")
    a = ap.parse_args()
    out = []
    for key, row, (model, name) in SYSTEMS:
        v = extra(model, name, "judge")
        hyp = {}
        for line in open(f"{R}/evals/{model}/extra/rows_{name}.jsonl", encoding="utf-8"):
            r = json.loads(line)
            hyp[r["id"]] = r.get("hyp_text") or ""
        n = len(v)
        c = collections.Counter(min(5, max(1, math.floor(x + 0.5))) for x in v.values())
        s = {k: 100.0 * c[k] / n for k in range(1, 6)}
        out.append({"key": key, "table1_row": row, "rows": f"{R}/evals/{model}/extra/{name}.judge.json.rows.jsonl",
                    "n": n, "mean": sum(v.values()) / n, "empty": 100.0 * sum(not hyp[i].strip() for i in v) / n,
                    **{f"s{k}": s[k] for k in range(1, 6)}, "ge3": s[3] + s[4] + s[5], "ge4": s[4] + s[5]})
    os.makedirs(os.path.dirname(a.json), exist_ok=True)
    json.dump({"bins": "expected judge score rounded to the nearest integer (x.5 up)", "systems": out},
              open(a.json, "w"), indent=1)
    d = os.path.join(a.paper, "figures", "judge")
    os.makedirs(d, exist_ok=True)
    cols = ["key", "n", "mean", "empty", "s1", "s2", "s3", "s4", "s5", "ge3", "ge4"]
    with open(os.path.join(d, "judge_dist.dat"), "w", encoding="utf-8") as fh:
        fh.write("% generated by scripts/paper/judge_dist_data.py (code repo); shares in % of documents\n")
        fh.write(" ".join(cols) + "\n")
        for x in out:
            fh.write(" ".join(x[c] if c == "key" else (str(x[c]) if c == "n" else f"{x[c]:.4f}") for c in cols) + "\n")
    for x in out:
        print(f"{x['key']:11s} n={x['n']:6d} mean={x['mean']:.3f} empty={x['empty']:.2f} "
              + " ".join(f"{k}:{x[f's{k}']:.2f}" for k in range(1, 6)) + f" >=3 {x['ge3']:.2f} >=4 {x['ge4']:.2f}")


if __name__ == "__main__":
    main()
